# coding: utf-8

"""
    openNPL API

    openNPL is an open source platform for the management of credit risk and non-performing loans. It implements detailed European Banking Authority loan templates for NPL data and US Agency Single Family Loan Performance Data

    The version of the OpenAPI document: v1
    Contact: info@openriskmanagement.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.api_api import ApiApi


class TestApiApi(unittest.TestCase):
    """ApiApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ApiApi()

    def tearDown(self) -> None:
        pass

    def test_api_list(self) -> None:
        """Test case for api_list

        """
        pass

    def test_api_npl_data_counterparties_create(self) -> None:
        """Test case for api_npl_data_counterparties_create

        """
        pass

    def test_api_npl_data_counterparties_list(self) -> None:
        """Test case for api_npl_data_counterparties_list

        """
        pass

    def test_api_npl_data_counterparties_read(self) -> None:
        """Test case for api_npl_data_counterparties_read

        """
        pass

    def test_api_npl_data_counterparty_groups_create(self) -> None:
        """Test case for api_npl_data_counterparty_groups_create

        """
        pass

    def test_api_npl_data_counterparty_groups_list(self) -> None:
        """Test case for api_npl_data_counterparty_groups_list

        """
        pass

    def test_api_npl_data_counterparty_groups_read(self) -> None:
        """Test case for api_npl_data_counterparty_groups_read

        """
        pass

    def test_api_npl_data_enforcement_create(self) -> None:
        """Test case for api_npl_data_enforcement_create

        """
        pass

    def test_api_npl_data_enforcement_list(self) -> None:
        """Test case for api_npl_data_enforcement_list

        """
        pass

    def test_api_npl_data_enforcement_read(self) -> None:
        """Test case for api_npl_data_enforcement_read

        """
        pass

    def test_api_npl_data_external_collection_create(self) -> None:
        """Test case for api_npl_data_external_collection_create

        """
        pass

    def test_api_npl_data_external_collection_list(self) -> None:
        """Test case for api_npl_data_external_collection_list

        """
        pass

    def test_api_npl_data_external_collection_read(self) -> None:
        """Test case for api_npl_data_external_collection_read

        """
        pass

    def test_api_npl_data_forbearance_create(self) -> None:
        """Test case for api_npl_data_forbearance_create

        """
        pass

    def test_api_npl_data_forbearance_list(self) -> None:
        """Test case for api_npl_data_forbearance_list

        """
        pass

    def test_api_npl_data_forbearance_read(self) -> None:
        """Test case for api_npl_data_forbearance_read

        """
        pass

    def test_api_npl_data_list(self) -> None:
        """Test case for api_npl_data_list

        Returns a list of all active API endpoints in the OpenNPL installation, grouped by functionality:
        """
        pass

    def test_api_npl_data_loans_create(self) -> None:
        """Test case for api_npl_data_loans_create

        """
        pass

    def test_api_npl_data_loans_list(self) -> None:
        """Test case for api_npl_data_loans_list

        """
        pass

    def test_api_npl_data_loans_read(self) -> None:
        """Test case for api_npl_data_loans_read

        """
        pass

    def test_api_npl_data_nonproperty_collateral_create(self) -> None:
        """Test case for api_npl_data_nonproperty_collateral_create

        """
        pass

    def test_api_npl_data_nonproperty_collateral_list(self) -> None:
        """Test case for api_npl_data_nonproperty_collateral_list

        """
        pass

    def test_api_npl_data_nonproperty_collateral_read(self) -> None:
        """Test case for api_npl_data_nonproperty_collateral_read

        """
        pass

    def test_api_npl_data_property_collateral_create(self) -> None:
        """Test case for api_npl_data_property_collateral_create

        """
        pass

    def test_api_npl_data_property_collateral_list(self) -> None:
        """Test case for api_npl_data_property_collateral_list

        """
        pass

    def test_api_npl_data_property_collateral_read(self) -> None:
        """Test case for api_npl_data_property_collateral_read

        """
        pass

    def test_api_sflp_data_counterparties_create(self) -> None:
        """Test case for api_sflp_data_counterparties_create

        """
        pass

    def test_api_sflp_data_counterparties_list(self) -> None:
        """Test case for api_sflp_data_counterparties_list

        """
        pass

    def test_api_sflp_data_counterparties_read(self) -> None:
        """Test case for api_sflp_data_counterparties_read

        """
        pass

    def test_api_sflp_data_enforcement_create(self) -> None:
        """Test case for api_sflp_data_enforcement_create

        """
        pass

    def test_api_sflp_data_enforcement_list(self) -> None:
        """Test case for api_sflp_data_enforcement_list

        """
        pass

    def test_api_sflp_data_enforcement_read(self) -> None:
        """Test case for api_sflp_data_enforcement_read

        """
        pass

    def test_api_sflp_data_forbearance_create(self) -> None:
        """Test case for api_sflp_data_forbearance_create

        """
        pass

    def test_api_sflp_data_forbearance_list(self) -> None:
        """Test case for api_sflp_data_forbearance_list

        """
        pass

    def test_api_sflp_data_forbearance_read(self) -> None:
        """Test case for api_sflp_data_forbearance_read

        """
        pass

    def test_api_sflp_data_list(self) -> None:
        """Test case for api_sflp_data_list

        """
        pass

    def test_api_sflp_data_loans_create(self) -> None:
        """Test case for api_sflp_data_loans_create

        """
        pass

    def test_api_sflp_data_loans_list(self) -> None:
        """Test case for api_sflp_data_loans_list

        """
        pass

    def test_api_sflp_data_loans_read(self) -> None:
        """Test case for api_sflp_data_loans_read

        """
        pass

    def test_api_sflp_data_property_collateral_create(self) -> None:
        """Test case for api_sflp_data_property_collateral_create

        """
        pass

    def test_api_sflp_data_property_collateral_list(self) -> None:
        """Test case for api_sflp_data_property_collateral_list

        """
        pass

    def test_api_sflp_data_property_collateral_read(self) -> None:
        """Test case for api_sflp_data_property_collateral_read

        """
        pass


if __name__ == '__main__':
    unittest.main()
