# coding: utf-8

# flake8: noqa
"""
    openNPL API

    openNPL is an open source platform for the management of credit risk and non-performing loans. It implements detailed European Banking Authority loan templates for NPL data and US Agency Single Family Loan Performance Data

    The version of the OpenAPI document: v1
    Contact: info@openriskmanagement.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package

